version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.4
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/buisiness-quiz-app
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    depends_on:
      - db
      - redis
      - selenium_chrome
    tty: true
    stdin_open: true
  selenium_chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444

volumes:
  db-data:
  api-bundle:
